// Generated by https://quicktype.io



export interface IMedicamento {
    resultados: any;
    nregistro?:                     string;
    nombre:                        string;
    labtitular:                    string;
    cpresc?:                        Cpresc;
    estado?:                        Estado;
    comerc?:                        boolean;
    receta?:                        boolean;
    generico?:                      boolean;
    conduc?:                        boolean;
    triangulo?:                     boolean;
    huerfano?:                      boolean;
    biosimilar?:                    boolean;
    nosustituible?:                 FormaFarmaceutica;
    psum?:                          boolean;
    notas?:                         boolean;
    materialesInf?:                 boolean;
    ema?:                           boolean;
    docs?:                          Doc[];
    fotos?:                         Foto[];
    viasAdministracion?:            FormaFarmaceutica[];
    formaFarmaceutica?:             FormaFarmaceutica;
    formaFarmaceuticaSimplificada?: FormaFarmaceutica;
    vtm?:                           FormaFarmaceutica;
    dosis?:                         string;
}

export enum Cpresc {
    MedicamentoSujetoAPrescripciónMédica = "Medicamento Sujeto A Prescripción Médica",
    MedicamentoSujetoAPrescripciónMédicaPsicótropos = "Medicamento Sujeto A Prescripción Médica. Psicótropos",
}

export interface Doc {
    tipo?:     number;
    url?:      string;
    secc?:     boolean;
    fecha?:    number;
    urlHtml?: string;
}

export interface Estado {
    aut?: number;
}

export interface FormaFarmaceutica {
    id?:     number;
    nombre?: string;
}

export interface Foto {
    tipo?:  Tipo;
    url?:   string;
    fecha?: number;
}

export enum Tipo {
    Formafarmac = "formafarmac",
    Materialas = "materialas",
}
