// Generated by https://quicktype.io

export interface IUsuarioResponse {
    id:                    number;
    avatar:                string;
    userName:              string;
    email:                 string;
    password:              string;
}
